### PR TITLE
Add support for multiple files and .css

### PR DESCRIPTION
**Pull request by kfwerf**
- Allow chunks
- Allow css

Hey i added some stuff to your plugin, i dont know if you want to use any of this but feel free to merge. Should help with support for common chunks and css. The search should probably be lighter tho, e.g. just search for src="app.js" or something should be fine.

Let me know what you think its just a small change :) to make it compatible with my webpack config

### CODE REVIEW

**Comment by joeyeng** [comment]
Hey kfwerf, can you send me an excerpt of your webpack config with the relevant bits, so I can see your setup? It's been a long time since I've touched webpack, so I'm trying to remember how it all works again, lol.

**Comment by kfwerf** [comment]
@giemch Hey Joey, no worries, it's a conf for webpack 2, it sort of looks like this, i sort of split between dev and prod so i tried merging the relevant bits into the config, hope it helps!

webpack.config.js
```
module.exports = {
  entry: {
    app: [
      resolve(__dirname, 'public/javascripts/app.js'),
    ],
    vendor = [
      'jquery',
      'underscore-min',
      'angular',
    ],
  },
  output: {
    pathinfo: true,
    publicPath: 'https://localhost:7000/',
  },
  plugins: [
    new CommonsChunkPlugin({
      name: 'vendor',
      filename: '[chunkhash].common.js',
      minChunks: Infinity,
    }),
    new ProvidePlugin({
      jQuery: 'jquery',
      $: 'jquery',
      'window.jQuery': 'jquery',
      'ST.$': 'jquery',
      'WaveSurfer': 'wavesurfer',
      'ResizeSensor': 'ResizeSensor',
    }),
    new AggressiveMergingPlugin(),
    new ExtractTextPlugin('[chunkhash].[name].css'),
    new NamedModulesPlugin(),
  ],
  target: 'web',
  performance: {
  },
  resolve: {
    modules: [
      'node_modules',
      resolve(__dirname, 'public/javascripts/lib'),
      resolve(__dirname, 'public/javascripts/'),
    ],
    alias: {
      'jQuery': resolve(__dirname, './node_modules/jquery'),
      '$': resolve(__dirname, './node_modules/jquery'),
      'angular': resolve(__dirname, './node_modules/angular'),
    },
    extensions: ['.js'],
  },
  module: {
    rules: [
      {
        test: /\.less$/,
        exclude: /node_modules/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'css-loader',
              options: {
                importLoaders: 1,
                sourceMap: true,
                minimize: true,
                url: false,
              },
            },
            {
              loader: 'less-loader',
              options: {
                LessPlugins: new LessAutoprefix(),
                sourceMap: true,
              },
            },
          ],
        }),
      },
      {
        test: /\.css/,
        exclude: /node_modules/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [
            {
              loader: 'css-loader',
              options: {
                importLoaders: 1,
                sourceMap: true,
                minimize: true,
                url: false,
              },
            },
          ],
        }),
      },
      {
        test: /\.js?$/,
        exclude: /node_modules/,
        use: [{
          loader: 'ng-annotate-loader',
          options: {
            es6: true,
          },
        }, 'babel-loader?cacheDirectory'],
      },
      {
        exclude: /node_modules/,
        test: /\.(jpe?g|png|gif|svg)$/,
        loader: 'url-loader?limit=10000&name=[path][name].[ext]',
      },
      {
        exclude: /node_modules/,
        test: /\.(eot|svg|ttf|woff|woff2)$/,
        loader: 'file-loader',
      },
    ],
  },
};
```

**Comment by joeyeng** [comment]
Hey Kenneth, I created a little test html file and js files to test out your changes, and I kept banging my head on why my html output didn't get updated with the chunkhashes. I finally realized that in my html file the script tags didn't have type text/javascript specified, so yea a lighter search would be a good idea. I'll go ahead and make that change. Thanks!

**Comment by kfwerf** [comment]
Thanks!

**Comment by joeyeng** [comment]
Hey Kenneth, I dunno if you're still using this plugin, but thought I'd let you know that after adding support for css someone submitted an issue that css doesn't work with chunkhashes. The css filename will just get the same chunkhash as the js bundle... not good. The solution is to use [contenthash] with ExtractTextPlugin instead of [chunkhash]. Instead of adding content hash support I created a separate plugin for this: https://www.npmjs.com/package/contenthash-replace-webpack-plugin

**Comment by joeyeng** [comment]
Also, let me know if it's cool with you if I remove the css support from this plugin.

**Pull request merged**
